# Generated by Django 5.2.8 on 2025-11-18 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.CharField(blank=True, help_text='Для fill-in-the-blank и sentence completion. Можно через запятую для нескольких вариантов', max_length=200, verbose_name='Правильный ответ (текст)'),
        ),
        migrations.AddField(
            model_name='question',
            name='matching_pairs',
            field=models.JSONField(blank=True, help_text='Формат: [{"left": "A", "right": "1"}, {"left": "B", "right": "2"}]', null=True, verbose_name='Пары для Matching'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single_choice', 'Multiple Choice (один ответ)'), ('multiple_choice', 'Multiple Choice (несколько ответов)'), ('matching', 'Matching (соответствие)'), ('fill_blank', 'Fill-in-the-blank (заполнение пропусков)'), ('true_false_ng', 'True/False/Not Given'), ('sentence_completion', 'Sentence completion')], default='single_choice', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='answers_detail',
            field=models.JSONField(blank=True, help_text='JSON с информацией о каждом ответе', null=True, verbose_name='Детали ответов'),
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.readingexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия экзамена',
                'verbose_name_plural': 'Сессии экзаменов',
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
